// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Tauron.Application.MgiProjectManager.Data;

namespace Tauron.Application.MgiProjectManager.Migrations
{
    [DbContext(typeof(DatabaseImpl))]
    internal class DatabaseImplModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
            #pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("Tauron.Application.MgiProjectManager.Data.Entitys.JobEntity", b =>
                                                                                               {
                                                                                                   b.Property<string>("Id")
                                                                                                    .ValueGeneratedOnAdd();

                                                                                                   b.Property<bool>("Importent");

                                                                                                   b.Property<bool>("IsActive");

                                                                                                   b.Property<string>("LongName");

                                                                                                   b.Property<int>("Status");

                                                                                                   b.Property<DateTime>("TargetDate");

                                                                                                   b.HasKey("Id");

                                                                                                   b.ToTable("JobEntities");
                                                                                               });

            modelBuilder.Entity("Tauron.Application.MgiProjectManager.Data.Entitys.JobRunEntity", b =>
                                                                                                  {
                                                                                                      b.Property<int>("Id")
                                                                                                       .ValueGeneratedOnAdd();

                                                                                                      b.Property<long>("Amount");

                                                                                                      b.Property<bool>("BigProblem");

                                                                                                      b.Property<TimeSpan>("EffectiveTime");

                                                                                                      b.Property<bool>("IsValid");

                                                                                                      b.Property<int?>("IterationTime");

                                                                                                      b.Property<long>("Iterations");

                                                                                                      b.Property<string>("JobId");

                                                                                                      b.Property<int>("Length");

                                                                                                      b.Property<TimeSpan>("NormaizedTime");

                                                                                                      b.Property<bool>("Problem");

                                                                                                      b.Property<int?>("SetupTime");

                                                                                                      b.Property<double>("Speed");

                                                                                                      b.Property<DateTime>("StartTime");

                                                                                                      b.Property<int>("Width");

                                                                                                      b.HasKey("Id");

                                                                                                      b.HasIndex("JobId")
                                                                                                       .IsUnique();

                                                                                                      b.ToTable("RunEntities");
                                                                                                  });

            modelBuilder.Entity("Tauron.Application.MgiProjectManager.Data.Entitys.JobRunEntity", b =>
                                                                                                  {
                                                                                                      b.HasOne("Tauron.Application.MgiProjectManager.Data.Entitys.JobEntity", "Job")
                                                                                                       .WithOne("JobRun")
                                                                                                       .HasForeignKey("Tauron.Application.MgiProjectManager.Data.Entitys.JobRunEntity", "JobId");
                                                                                                  });
            #pragma warning restore 612, 618
        }
    }
}