//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tauron.Application.ProjectManager.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MainUIResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainUIResources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tauron.Application.ProjectManager.Resources.MainUIResources", typeof(MainUIResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Calculate ähnelt.
        /// </summary>
        public static string BtnTimeCalculate {
            get {
                return ResourceManager.GetString("BtnTimeCalculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Next ähnelt.
        /// </summary>
        public static string Common_Label_Next {
            get {
                return ResourceManager.GetString("Common_Label_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OK ähnelt.
        /// </summary>
        public static string CommonLabelOk {
            get {
                return ResourceManager.GetString("CommonLabelOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        public static string JobCreationView_Label_CommonError {
            get {
                return ResourceManager.GetString("JobCreationView_Label_CommonError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Is Importent ? ähnelt.
        /// </summary>
        public static string JobCreationView_Label_IsImportetSelector {
            get {
                return ResourceManager.GetString("JobCreationView_Label_IsImportetSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Target Date: ähnelt.
        /// </summary>
        public static string JobCreationView_Label_JobDate {
            get {
                return ResourceManager.GetString("JobCreationView_Label_JobDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select Target Date ähnelt.
        /// </summary>
        public static string JobCreationView_Label_SelectTargetDate {
            get {
                return ResourceManager.GetString("JobCreationView_Label_SelectTargetDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        public static string JobCreationViewModel_Label_Next {
            get {
                return ResourceManager.GetString("JobCreationViewModel_Label_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Iteration Time ähnelt.
        /// </summary>
        public static string LabelTimeCalcIterationTime {
            get {
                return ResourceManager.GetString("LabelTimeCalcIterationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Runtime: ähnelt.
        /// </summary>
        public static string LabelTimeCalcRuntime {
            get {
                return ResourceManager.GetString("LabelTimeCalcRuntime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Setup ähnelt.
        /// </summary>
        public static string LabelTimeCalcSetupTime {
            get {
                return ResourceManager.GetString("LabelTimeCalcSetupTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Compled Time: ähnelt.
        /// </summary>
        public static string LabelTimeCompled {
            get {
                return ResourceManager.GetString("LabelTimeCompled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Data ähnelt.
        /// </summary>
        public static string LabelTimeData {
            get {
                return ResourceManager.GetString("LabelTimeData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mikron: ähnelt.
        /// </summary>
        public static string LabelTimeMikron {
            get {
                return ResourceManager.GetString("LabelTimeMikron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Amount: ähnelt.
        /// </summary>
        public static string LabelTimeNumber {
            get {
                return ResourceManager.GetString("LabelTimeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Paper Format: ähnelt.
        /// </summary>
        public static string LabelTimePaperFormat {
            get {
                return ResourceManager.GetString("LabelTimePaperFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Result ähnelt.
        /// </summary>
        public static string LabelTimeResult {
            get {
                return ResourceManager.GetString("LabelTimeResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Runs: ähnelt.
        /// </summary>
        public static string LabelTimeRuns {
            get {
                return ResourceManager.GetString("LabelTimeRuns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Saving Job Data ähnelt.
        /// </summary>
        public static string LabelTimeSaveJobTime {
            get {
                return ResourceManager.GetString("LabelTimeSaveJobTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Saving Compled ähnelt.
        /// </summary>
        public static string LabelTimeSaveJobTimeSuccess {
            get {
                return ResourceManager.GetString("LabelTimeSaveJobTimeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Setup Time: ähnelt.
        /// </summary>
        public static string LabelTimeSetupTime {
            get {
                return ResourceManager.GetString("LabelTimeSetupTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Speed: ähnelt.
        /// </summary>
        public static string LabelTimeSpeed {
            get {
                return ResourceManager.GetString("LabelTimeSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Status: ähnelt.
        /// </summary>
        public static string LabelTimeStatus {
            get {
                return ResourceManager.GetString("LabelTimeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create Job ähnelt.
        /// </summary>
        public static string MainWindow_Button_CreateJob {
            get {
                return ResourceManager.GetString("MainWindow_Button_CreateJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mark As Importent ähnelt.
        /// </summary>
        public static string MainWindow_Button_MarkAsImportent {
            get {
                return ResourceManager.GetString("MainWindow_Button_MarkAsImportent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Close ähnelt.
        /// </summary>
        public static string MainWindow_MenuButton_Close {
            get {
                return ResourceManager.GetString("MainWindow_MenuButton_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File ähnelt.
        /// </summary>
        public static string MainWindow_MenuLabel_File {
            get {
                return ResourceManager.GetString("MainWindow_MenuLabel_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reconnect ähnelt.
        /// </summary>
        public static string MainWindow_MenuLabel_Reconnect {
            get {
                return ResourceManager.GetString("MainWindow_MenuLabel_Reconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Server ähnelt.
        /// </summary>
        public static string MainWindow_MenuLabel_Server {
            get {
                return ResourceManager.GetString("MainWindow_MenuLabel_Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show Login Window ähnelt.
        /// </summary>
        public static string MainWindow_MenuLabel_ShowLogin {
            get {
                return ResourceManager.GetString("MainWindow_MenuLabel_ShowLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fetching Data... ähnelt.
        /// </summary>
        public static string MainWindowModel_Label_Connecting {
            get {
                return ResourceManager.GetString("MainWindowModel_Label_Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Connection Failed ähnelt.
        /// </summary>
        public static string MainWindowModel_Label_ConnectionFailed {
            get {
                return ResourceManager.GetString("MainWindowModel_Label_ConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Logging In ähnelt.
        /// </summary>
        public static string MainWindowModel_Label_Login {
            get {
                return ResourceManager.GetString("MainWindowModel_Label_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Status: OK ähnelt.
        /// </summary>
        public static string MainWindowModel_Label_StatusOk {
            get {
                return ResourceManager.GetString("MainWindowModel_Label_StatusOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Operation Failed ähnelt.
        /// </summary>
        public static string MainWindowViewModel_Label_FinlizeFailed {
            get {
                return ResourceManager.GetString("MainWindowViewModel_Label_FinlizeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Extrapolation with low reliability ähnelt.
        /// </summary>
        public static string PrecisionModeAmountMismatchNearCorner {
            get {
                return ResourceManager.GetString("PrecisionModeAmountMismatchNearCorner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Extrapolation with medium reliability ähnelt.
        /// </summary>
        public static string PrecisionModeAmountMismatchPerfect {
            get {
                return ResourceManager.GetString("PrecisionModeAmountMismatchPerfect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Medium reliability ähnelt.
        /// </summary>
        public static string PrecisionModeNearCorner {
            get {
                return ResourceManager.GetString("PrecisionModeNearCorner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No Data ähnelt.
        /// </summary>
        public static string PrecisionModeNoData {
            get {
                return ResourceManager.GetString("PrecisionModeNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die High reliability ähnelt.
        /// </summary>
        public static string PrecisionModePerfect {
            get {
                return ResourceManager.GetString("PrecisionModePerfect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Compled ähnelt.
        /// </summary>
        public static string StatusConverter_StatusCompled {
            get {
                return ResourceManager.GetString("StatusConverter_StatusCompled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Creation ähnelt.
        /// </summary>
        public static string StatusConverter_StatusCreation {
            get {
                return ResourceManager.GetString("StatusConverter_StatusCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Drying ähnelt.
        /// </summary>
        public static string StatusConverter_StatusDrying {
            get {
                return ResourceManager.GetString("StatusConverter_StatusDrying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die In Progress ähnelt.
        /// </summary>
        public static string StatusConverter_StatusInProgress {
            get {
                return ResourceManager.GetString("StatusConverter_StatusInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pending ähnelt.
        /// </summary>
        public static string StatusConverter_StatusPending {
            get {
                return ResourceManager.GetString("StatusConverter_StatusPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Prepare ähnelt.
        /// </summary>
        public static string StatusConverter_StatusPrepare {
            get {
                return ResourceManager.GetString("StatusConverter_StatusPrepare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fetching Jobs ähnelt.
        /// </summary>
        public static string TaskFetchJobs {
            get {
                return ResourceManager.GetString("TaskFetchJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Runtime Calculation ähnelt.
        /// </summary>
        public static string TimeCalcRuntimeCalculation {
            get {
                return ResourceManager.GetString("TimeCalcRuntimeCalculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The last Values only in 5 cm steps ähnelt.
        /// </summary>
        public static string TimeFormatToolTip {
            get {
                return ResourceManager.GetString("TimeFormatToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Time is calculating ähnelt.
        /// </summary>
        public static string TitleTimeCalcCalculation {
            get {
                return ResourceManager.GetString("TitleTimeCalcCalculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Paper Format ähnelt.
        /// </summary>
        public static string WaterLabelPaperFormat {
            get {
                return ResourceManager.GetString("WaterLabelPaperFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Runs ähnelt.
        /// </summary>
        public static string WaterLabelRuns {
            get {
                return ResourceManager.GetString("WaterLabelRuns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mikron ähnelt.
        /// </summary>
        public static string WaterLabelTimeMikron {
            get {
                return ResourceManager.GetString("WaterLabelTimeMikron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Amount ähnelt.
        /// </summary>
        public static string WaterLabelTimeNumber {
            get {
                return ResourceManager.GetString("WaterLabelTimeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Speed ähnelt.
        /// </summary>
        public static string WaterLabelTimeSpeed {
            get {
                return ResourceManager.GetString("WaterLabelTimeSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create Job ähnelt.
        /// </summary>
        public static string WindowTitelCreateJob {
            get {
                return ResourceManager.GetString("WindowTitelCreateJob", resourceCulture);
            }
        }
    }
}
