//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tauron.Application.ProjectManager.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ServiceErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ServiceErrorMessages() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tauron.Application.ProjectManager.Resources.ServiceErrorMessages", typeof(ServiceErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Job Is Already Insertet. ähnelt.
        /// </summary>
        public static string AssertJobIsAlreadyInsertet {
            get {
                return ResourceManager.GetString("AssertJobIsAlreadyInsertet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Job Name Is Invalid ähnelt.
        /// </summary>
        public static string AssertJobNameInvalid {
            get {
                return ResourceManager.GetString("AssertJobNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Authorization Faild: ähnelt.
        /// </summary>
        public static string Authorization_Error {
            get {
                return ResourceManager.GetString("Authorization_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Connection Failed ähnelt.
        /// </summary>
        public static string ConnectionFailed {
            get {
                return ResourceManager.GetString("ConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Session Is Alredy Registered ähnelt.
        /// </summary>
        public static string ConnectivityManager_Session_AlreadyRegistered {
            get {
                return ResourceManager.GetString("ConnectivityManager_Session_AlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Amount was not set. ähnelt.
        /// </summary>
        public static string TimeCalcAmountNull {
            get {
                return ResourceManager.GetString("TimeCalcAmountNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Amount must be greater than 1. ähnelt.
        /// </summary>
        public static string TimeCalcAmountToLow {
            get {
                return ResourceManager.GetString("TimeCalcAmountToLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Format maximum 52 x 100. ähnelt.
        /// </summary>
        public static string TimeCalcFormatToLarge {
            get {
                return ResourceManager.GetString("TimeCalcFormatToLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Format at least A4. ähnelt.
        /// </summary>
        public static string TimeCalcFormatToSmall {
            get {
                return ResourceManager.GetString("TimeCalcFormatToSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Passes was not set. ähnelt.
        /// </summary>
        public static string TimeCalcIterationNull {
            get {
                return ResourceManager.GetString("TimeCalcIterationNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pass must have at least 1. ähnelt.
        /// </summary>
        public static string TimeCalcIterationToLow {
            get {
                return ResourceManager.GetString("TimeCalcIterationToLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Paper Format Specified Incorrect. ähnelt.
        /// </summary>
        public static string TimeCalcPaperFormatWrong {
            get {
                return ResourceManager.GetString("TimeCalcPaperFormatWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Speed ​​must be at least 0.06. ähnelt.
        /// </summary>
        public static string TimeCalcSpeedLow {
            get {
                return ResourceManager.GetString("TimeCalcSpeedLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Speed ​​was not set. ähnelt.
        /// </summary>
        public static string TimeCalcSpeedNull {
            get {
                return ResourceManager.GetString("TimeCalcSpeedNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Speed ​​may not exceed 0.7. ähnelt.
        /// </summary>
        public static string TimeCalcSpeeHight {
            get {
                return ResourceManager.GetString("TimeCalcSpeeHight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The running time must be over 1 second. ähnelt.
        /// </summary>
        public static string TimeCalcTimeLow {
            get {
                return ResourceManager.GetString("TimeCalcTimeLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No data available. ähnelt.
        /// </summary>
        public static string TimeCalculationNoDataLabel {
            get {
                return ResourceManager.GetString("TimeCalculationNoDataLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unable to Delete User ähnelt.
        /// </summary>
        public static string UserManager_Reason_Delete {
            get {
                return ResourceManager.GetString("UserManager_Reason_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No Password Set ähnelt.
        /// </summary>
        public static string UserManager_Reason_NoPassword {
            get {
                return ResourceManager.GetString("UserManager_Reason_NoPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No User Found ähnelt.
        /// </summary>
        public static string UserManager_Reason_NoUser {
            get {
                return ResourceManager.GetString("UserManager_Reason_NoUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Password Wrong ähnelt.
        /// </summary>
        public static string UserManager_Reason_PasswordMismatch {
            get {
                return ResourceManager.GetString("UserManager_Reason_PasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The Password is Null ähnelt.
        /// </summary>
        public static string UserManager_Reason_PasswordNull {
            get {
                return ResourceManager.GetString("UserManager_Reason_PasswordNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The already exis ähnelt.
        /// </summary>
        public static string UserManager_Reason_UserExis {
            get {
                return ResourceManager.GetString("UserManager_Reason_UserExis", resourceCulture);
            }
        }
    }
}
