//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tauron.Application.MgiProjectManager.Resources.Web {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WebResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebResources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tauron.Application.MgiProjectManager.Resources.Web.WebResources", typeof(WebResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cookies Need To work with this Site. ähnelt.
        /// </summary>
        public static string _CookieConsentPartial_Summery {
            get {
                return ResourceManager.GetString("_CookieConsentPartial_Summery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Change your account settings ähnelt.
        /// </summary>
        public static string _Layout_Account_Text {
            get {
                return ResourceManager.GetString("_Layout_Account_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Manage your account ähnelt.
        /// </summary>
        public static string _Layout_Account_Text_Title {
            get {
                return ResourceManager.GetString("_Layout_Account_Text_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lanuguages ähnelt.
        /// </summary>
        public static string _Layout_DropDown_Language {
            get {
                return ResourceManager.GetString("_Layout_DropDown_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Home ähnelt.
        /// </summary>
        public static string _Layout_Link_Home {
            get {
                return ResourceManager.GetString("_Layout_Link_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Privacy ähnelt.
        /// </summary>
        public static string _Layout_Link_Privacy {
            get {
                return ResourceManager.GetString("_Layout_Link_Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hello {0} ähnelt.
        /// </summary>
        public static string _LoginPatial_Text_Hello {
            get {
                return ResourceManager.GetString("_LoginPatial_Text_Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Profile ähnelt.
        /// </summary>
        public static string _ManageNav_Account_Profile {
            get {
                return ResourceManager.GetString("_ManageNav_Account_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You do not have access to this resource. ähnelt.
        /// </summary>
        public static string AccessDenied_Text {
            get {
                return ResourceManager.GetString("AccessDenied_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Access Denied ähnelt.
        /// </summary>
        public static string AccessDenied_Text_Title {
            get {
                return ResourceManager.GetString("AccessDenied_Text_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Change Password ähnelt.
        /// </summary>
        public static string Account_ChangedPassord_Title {
            get {
                return ResourceManager.GetString("Account_ChangedPassord_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update Password ähnelt.
        /// </summary>
        public static string Account_ChangedPassword_UpdatePassword {
            get {
                return ResourceManager.GetString("Account_ChangedPassword_UpdatePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete data and close my account ähnelt.
        /// </summary>
        public static string Account_DeletePersonalData_Button {
            get {
                return ResourceManager.GetString("Account_DeletePersonalData_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deleting this data will permanently remove your account, and this cannot be recovered. ähnelt.
        /// </summary>
        public static string Account_DeletePersonalData_Text {
            get {
                return ResourceManager.GetString("Account_DeletePersonalData_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete Personal Data ähnelt.
        /// </summary>
        public static string Account_DeletePersonalData_Title {
            get {
                return ResourceManager.GetString("Account_DeletePersonalData_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unexpected error occurred deleteing user with ID &apos;{0}&apos;. ähnelt.
        /// </summary>
        public static string Account_DeletePersonalData_UnexpectError {
            get {
                return ResourceManager.GetString("Account_DeletePersonalData_UnexpectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unable to load user with ID &apos;{0}&apos;. ähnelt.
        /// </summary>
        public static string Account_DeletePersonalData_UserNotFound {
            get {
                return ResourceManager.GetString("Account_DeletePersonalData_UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Password not correct. ähnelt.
        /// </summary>
        public static string Account_DeletePersonalData_WrongPassword {
            get {
                return ResourceManager.GetString("Account_DeletePersonalData_WrongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Download Your Data ähnelt.
        /// </summary>
        public static string Account_DownloadPersonalData_Title {
            get {
                return ResourceManager.GetString("Account_DownloadPersonalData_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Generate two-factor authentication (2FA) recovery codes ähnelt.
        /// </summary>
        public static string Account_GenerateRecoveryCode_Title {
            get {
                return ResourceManager.GetString("Account_GenerateRecoveryCode_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Password ähnelt.
        /// </summary>
        public static string Account_ManageNav_Password {
            get {
                return ResourceManager.GetString("Account_ManageNav_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Personal Data ähnelt.
        /// </summary>
        public static string Account_ManageNav_PersonalData {
            get {
                return ResourceManager.GetString("Account_ManageNav_PersonalData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Accept ähnelt.
        /// </summary>
        public static string Base_Text_Accept {
            get {
                return ResourceManager.GetString("Base_Text_Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Learn More ähnelt.
        /// </summary>
        public static string Base_Text_LearnMore {
            get {
                return ResourceManager.GetString("Base_Text_LearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Thank you for confirming your email. ähnelt.
        /// </summary>
        public static string ConfirmEmail_Text {
            get {
                return ResourceManager.GetString("ConfirmEmail_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Confirm E-mail ähnelt.
        /// </summary>
        public static string ConfirmEmail_Text_Title {
            get {
                return ResourceManager.GetString("ConfirmEmail_Text_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Recovery Code ähnelt.
        /// </summary>
        public static string Data_Display_RecoveryCode {
            get {
                return ResourceManager.GetString("Data_Display_RecoveryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remember Me? ähnelt.
        /// </summary>
        public static string Data_Display_RememberMe {
            get {
                return ResourceManager.GetString("Data_Display_RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter a valid E-mail Adress. {0} ähnelt.
        /// </summary>
        public static string Data_EmailAddress_Invalid {
            get {
                return ResourceManager.GetString("Data_EmailAddress_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The Field {0} is Required. ähnelt.
        /// </summary>
        public static string Data_Required {
            get {
                return ResourceManager.GetString("Data_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The {0} must be at least {2} and at max {1} characters long. ähnelt.
        /// </summary>
        public static string Data_StringLenght {
            get {
                return ResourceManager.GetString("Data_StringLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An error occurred while processing your request. ähnelt.
        /// </summary>
        public static string Error_Text {
            get {
                return ResourceManager.GetString("Error_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        public static string Error_Text_Title {
            get {
                return ResourceManager.GetString("Error_Text_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Submit ähnelt.
        /// </summary>
        public static string ForgotPassword_Button_Submit {
            get {
                return ResourceManager.GetString("ForgotPassword_Button_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reset Password ähnelt.
        /// </summary>
        public static string ForgotPassword_ResetEmail_Subject {
            get {
                return ResourceManager.GetString("ForgotPassword_ResetEmail_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please reset your password by &lt;a href=&apos;{0}&apos;&gt;clicking here&lt;/a&gt;. ähnelt.
        /// </summary>
        public static string ForgotPassword_ResetMail_Body {
            get {
                return ResourceManager.GetString("ForgotPassword_ResetMail_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter yout Email ähnelt.
        /// </summary>
        public static string ForgotPassword_Text_EnterEmail {
            get {
                return ResourceManager.GetString("ForgotPassword_Text_EnterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Forgot your Password? ähnelt.
        /// </summary>
        public static string ForgotPassword_Text_Title {
            get {
                return ResourceManager.GetString("ForgotPassword_Text_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please check your email to reset your password. ähnelt.
        /// </summary>
        public static string ForgotPasswordConfomation_Text {
            get {
                return ResourceManager.GetString("ForgotPasswordConfomation_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Forgot password confirmation ähnelt.
        /// </summary>
        public static string ForgotPasswordConfomation_Text_Title {
            get {
                return ResourceManager.GetString("ForgotPasswordConfomation_Text_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Welcome ähnelt.
        /// </summary>
        public static string Index_Header_Welcome {
            get {
                return ResourceManager.GetString("Index_Header_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This account has been locked out, please try again later. ähnelt.
        /// </summary>
        public static string Lockout_Text {
            get {
                return ResourceManager.GetString("Lockout_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lock out ähnelt.
        /// </summary>
        public static string Lockout_Text_Title {
            get {
                return ResourceManager.GetString("Lockout_Text_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Log In ähnelt.
        /// </summary>
        public static string Login_Button_Login {
            get {
                return ResourceManager.GetString("Login_Button_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Login with Local Account. ähnelt.
        /// </summary>
        public static string Login_Form_Header {
            get {
                return ResourceManager.GetString("Login_Form_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Forgot Password? ähnelt.
        /// </summary>
        public static string Login_Text_ForgotPassword {
            get {
                return ResourceManager.GetString("Login_Text_ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid login attempt. ähnelt.
        /// </summary>
        public static string Login_Text_LoginError {
            get {
                return ResourceManager.GetString("Login_Text_LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Log In ähnelt.
        /// </summary>
        public static string Login_Text_Title {
            get {
                return ResourceManager.GetString("Login_Text_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Log In ähnelt.
        /// </summary>
        public static string LoginWithRecuveryCode_Button_Login {
            get {
                return ResourceManager.GetString("LoginWithRecuveryCode_Button_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid recovery code entered. ähnelt.
        /// </summary>
        public static string LoginWithRecuveryCode_InvalidCode {
            get {
                return ResourceManager.GetString("LoginWithRecuveryCode_InvalidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die     You have requested to log in with a recovery code. This login will not be remembered until you provide
        ///    an authenticator app code at log in or disable 2FA and log in again. ähnelt.
        /// </summary>
        public static string LoginWithRecuveryCode_Text {
            get {
                return ResourceManager.GetString("LoginWithRecuveryCode_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Recovery code verification ähnelt.
        /// </summary>
        public static string LoginWithRecuveryCode_Text_Title {
            get {
                return ResourceManager.GetString("LoginWithRecuveryCode_Text_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You have successfully logged out of the application. ähnelt.
        /// </summary>
        public static string Logout_Text {
            get {
                return ResourceManager.GetString("Logout_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Log out ähnelt.
        /// </summary>
        public static string Logout_Text_Title {
            get {
                return ResourceManager.GetString("Logout_Text_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reset ähnelt.
        /// </summary>
        public static string ResetPassowrt_Button {
            get {
                return ResourceManager.GetString("ResetPassowrt_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The password and confirmation password do not match. ähnelt.
        /// </summary>
        public static string ResetPassword_Data_ComparePassword {
            get {
                return ResourceManager.GetString("ResetPassword_Data_ComparePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Confirm password ähnelt.
        /// </summary>
        public static string ResetPassword_Data_ConfirmPassword {
            get {
                return ResourceManager.GetString("ResetPassword_Data_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reset your Password. ähnelt.
        /// </summary>
        public static string ResetPassword_Text_Header {
            get {
                return ResourceManager.GetString("ResetPassword_Text_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A code must be supplied for password reset. ähnelt.
        /// </summary>
        public static string ResetPassword_Text_NoCode {
            get {
                return ResourceManager.GetString("ResetPassword_Text_NoCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reset Password ähnelt.
        /// </summary>
        public static string ResetPassword_Text_Title {
            get {
                return ResourceManager.GetString("ResetPassword_Text_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your password has been reset. Please &lt;a href=&quot;{0}&quot;&gt;click here to log in&lt;/a&gt;. ähnelt.
        /// </summary>
        public static string ResetPasswordConfirmation_Text {
            get {
                return ResourceManager.GetString("ResetPasswordConfirmation_Text", resourceCulture);
            }
        }
    }
}
