//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tauron.MgiProjectManager.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ContractsRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ContractsRes() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tauron.MgiProjectManager.Resources.ContractsRes", typeof(ContractsRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Assign Role ähnelt.
        /// </summary>
        public static string ApplicationPermission_AssignRole {
            get {
                return ResourceManager.GetString("ApplicationPermission_AssignRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Permission to assign roles to users ähnelt.
        /// </summary>
        public static string ApplicationPermission_AssignRole_Description {
            get {
                return ResourceManager.GetString("ApplicationPermission_AssignRole_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Download Files ähnelt.
        /// </summary>
        public static string ApplicationPermission_Files_DownloadFiles {
            get {
                return ResourceManager.GetString("ApplicationPermission_Files_DownloadFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Permission to download data ähnelt.
        /// </summary>
        public static string ApplicationPermission_Files_DownloadFiles_Description {
            get {
                return ResourceManager.GetString("ApplicationPermission_Files_DownloadFiles_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File Manager ähnelt.
        /// </summary>
        public static string ApplicationPermission_Files_GroupName {
            get {
                return ResourceManager.GetString("ApplicationPermission_Files_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Upload Files ähnelt.
        /// </summary>
        public static string ApplicationPermission_Files_UploadFiles {
            get {
                return ResourceManager.GetString("ApplicationPermission_Files_UploadFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Permission to upload data ähnelt.
        /// </summary>
        public static string ApplicationPermission_Files_UploadFiles_Description {
            get {
                return ResourceManager.GetString("ApplicationPermission_Files_UploadFiles_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Manage Roles ähnelt.
        /// </summary>
        public static string ApplicationPermission_ManageRoles {
            get {
                return ResourceManager.GetString("ApplicationPermission_ManageRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Permission to create, delete and modify roles ähnelt.
        /// </summary>
        public static string ApplicationPermission_ManageRoles_Description {
            get {
                return ResourceManager.GetString("ApplicationPermission_ManageRoles_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Permission to create, delete and modify other users account details ähnelt.
        /// </summary>
        public static string ApplicationPermission_ManageUser_Description {
            get {
                return ResourceManager.GetString("ApplicationPermission_ManageUser_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Role Premissions ähnelt.
        /// </summary>
        public static string ApplicationPermission_RolesPermission_GroupName {
            get {
                return ResourceManager.GetString("ApplicationPermission_RolesPermission_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die View Roles ähnelt.
        /// </summary>
        public static string ApplicationPermission_ViewRoles {
            get {
                return ResourceManager.GetString("ApplicationPermission_ViewRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Permission to view available roles ähnelt.
        /// </summary>
        public static string ApplicationPermission_ViewRoles_Description {
            get {
                return ResourceManager.GetString("ApplicationPermission_ViewRoles_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die User Permissions ähnelt.
        /// </summary>
        public static string ApplicationPermission_ViewUsers_GroupName {
            get {
                return ResourceManager.GetString("ApplicationPermission_ViewUsers_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Permission to view other users account details ähnelt.
        /// </summary>
        public static string ApplicationPermissions_ViewUsers_Description {
            get {
                return ResourceManager.GetString("ApplicationPermissions_ViewUsers_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Manage Users ähnelt.
        /// </summary>
        public static string ApplicationPermissons_ManageUser {
            get {
                return ResourceManager.GetString("ApplicationPermissons_ManageUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die View Users ähnelt.
        /// </summary>
        public static string ApplicationPermissons_ViewUsers {
            get {
                return ResourceManager.GetString("ApplicationPermissons_ViewUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Role name is required ähnelt.
        /// </summary>
        public static string Models_Api_RoleViewModel_Name_Empty {
            get {
                return ResourceManager.GetString("Models_Api_RoleViewModel_Name_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Role name must be between 2 and 200 characters ähnelt.
        /// </summary>
        public static string Models_Api_RoleViewModel_Name_Lenght {
            get {
                return ResourceManager.GetString("Models_Api_RoleViewModel_Name_Lenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New Password must be at least 6 characters ähnelt.
        /// </summary>
        public static string Models_Api_UserEditViewModel_NewPassword_Lenght {
            get {
                return ResourceManager.GetString("Models_Api_UserEditViewModel_NewPassword_Lenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Roles cannot be empty ähnelt.
        /// </summary>
        public static string Models_Api_UserViewModel_Roles_Lenght {
            get {
                return ResourceManager.GetString("Models_Api_UserViewModel_Roles_Lenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Username cannot be empty ähnelt.
        /// </summary>
        public static string Models_Api_UserViewModel_UserName_Empty {
            get {
                return ResourceManager.GetString("Models_Api_UserViewModel_UserName_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Email is required ähnelt.
        /// </summary>
        public static string Models_Api_UserViewModelBase_Email_Empty {
            get {
                return ResourceManager.GetString("Models_Api_UserViewModelBase_Email_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid email address ähnelt.
        /// </summary>
        public static string Models_Api_UserViewModelBase_Email_Invalid {
            get {
                return ResourceManager.GetString("Models_Api_UserViewModelBase_Email_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Email must be at most 200 characters ähnelt.
        /// </summary>
        public static string Models_Api_UserViewModelBase_Email_Lenght {
            get {
                return ResourceManager.GetString("Models_Api_UserViewModelBase_Email_Lenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Username must be between 2 and 200 characters ähnelt.
        /// </summary>
        public static string Models_Api_UserViewModelBase_UserName_Lenght {
            get {
                return ResourceManager.GetString("Models_Api_UserViewModelBase_UserName_Lenght", resourceCulture);
            }
        }
    }
}
