//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tauron.Application.MgiProjectManager.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UIResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIResources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tauron.Application.MgiProjectManager.Resources.UIResources", typeof(UIResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Job Is Already Insertet. ähnelt.
        /// </summary>
        internal static string AssertJobIsAlreadyInsertet {
            get {
                return ResourceManager.GetString("AssertJobIsAlreadyInsertet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Job Name Is Invalid ähnelt.
        /// </summary>
        internal static string AssertJobNameInvalid {
            get {
                return ResourceManager.GetString("AssertJobNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create Job ähnelt.
        /// </summary>
        internal static string BtnCreateJob {
            get {
                return ResourceManager.GetString("BtnCreateJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mark As Importent ähnelt.
        /// </summary>
        internal static string BtnMarkAsImportent {
            get {
                return ResourceManager.GetString("BtnMarkAsImportent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Calculate ähnelt.
        /// </summary>
        internal static string BtnTimeCalculate {
            get {
                return ResourceManager.GetString("BtnTimeCalculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OK ähnelt.
        /// </summary>
        internal static string CommonLabelOk {
            get {
                return ResourceManager.GetString("CommonLabelOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        internal static string JobCreationNextLabel {
            get {
                return ResourceManager.GetString("JobCreationNextLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        internal static string LabelCommonError {
            get {
                return ResourceManager.GetString("LabelCommonError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Next ähnelt.
        /// </summary>
        internal static string LabelCommonNext {
            get {
                return ResourceManager.GetString("LabelCommonNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Is Importent ähnelt.
        /// </summary>
        internal static string LabelIsImportetSelector {
            get {
                return ResourceManager.GetString("LabelIsImportetSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Target Date: ähnelt.
        /// </summary>
        internal static string LabelJobDate {
            get {
                return ResourceManager.GetString("LabelJobDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select Target Date ähnelt.
        /// </summary>
        internal static string LabelSelectTargetDate {
            get {
                return ResourceManager.GetString("LabelSelectTargetDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Iteration Time ähnelt.
        /// </summary>
        internal static string LabelTimeCalcIterationTime {
            get {
                return ResourceManager.GetString("LabelTimeCalcIterationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Normalized time ähnelt.
        /// </summary>
        internal static string LabelTimeCalcNormalizedTime {
            get {
                return ResourceManager.GetString("LabelTimeCalcNormalizedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die per Thousand ähnelt.
        /// </summary>
        internal static string LabelTimeCalcPerThousand {
            get {
                return ResourceManager.GetString("LabelTimeCalcPerThousand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Runtime: ähnelt.
        /// </summary>
        internal static string LabelTimeCalcRuntime {
            get {
                return ResourceManager.GetString("LabelTimeCalcRuntime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Setup ähnelt.
        /// </summary>
        internal static string LabelTimeCalcSetupTime {
            get {
                return ResourceManager.GetString("LabelTimeCalcSetupTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Compled Time: ähnelt.
        /// </summary>
        internal static string LabelTimeCompled {
            get {
                return ResourceManager.GetString("LabelTimeCompled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Data ähnelt.
        /// </summary>
        internal static string LabelTimeData {
            get {
                return ResourceManager.GetString("LabelTimeData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mikron: ähnelt.
        /// </summary>
        internal static string LabelTimeMikron {
            get {
                return ResourceManager.GetString("LabelTimeMikron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Amount: ähnelt.
        /// </summary>
        internal static string LabelTimeNumber {
            get {
                return ResourceManager.GetString("LabelTimeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Paper Format: ähnelt.
        /// </summary>
        internal static string LabelTimePaperFormat {
            get {
                return ResourceManager.GetString("LabelTimePaperFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Result ähnelt.
        /// </summary>
        internal static string LabelTimeResult {
            get {
                return ResourceManager.GetString("LabelTimeResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Runs: ähnelt.
        /// </summary>
        internal static string LabelTimeRuns {
            get {
                return ResourceManager.GetString("LabelTimeRuns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Saving Job Data ähnelt.
        /// </summary>
        internal static string LabelTimeSaveJobTime {
            get {
                return ResourceManager.GetString("LabelTimeSaveJobTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Saving Compled ähnelt.
        /// </summary>
        internal static string LabelTimeSaveJobTimeSuccess {
            get {
                return ResourceManager.GetString("LabelTimeSaveJobTimeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Setup Time: ähnelt.
        /// </summary>
        internal static string LabelTimeSetupTime {
            get {
                return ResourceManager.GetString("LabelTimeSetupTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Speed: ähnelt.
        /// </summary>
        internal static string LabelTimeSpeed {
            get {
                return ResourceManager.GetString("LabelTimeSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Status: ähnelt.
        /// </summary>
        internal static string LabelTimeStatus {
            get {
                return ResourceManager.GetString("LabelTimeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Extrapolation with low reliability ähnelt.
        /// </summary>
        internal static string PrecisionModeAmountMismatchNearCorner {
            get {
                return ResourceManager.GetString("PrecisionModeAmountMismatchNearCorner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Extrapolation with medium reliability ähnelt.
        /// </summary>
        internal static string PrecisionModeAmountMismatchPerfect {
            get {
                return ResourceManager.GetString("PrecisionModeAmountMismatchPerfect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Medium reliability ähnelt.
        /// </summary>
        internal static string PrecisionModeNearCorner {
            get {
                return ResourceManager.GetString("PrecisionModeNearCorner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No Data ähnelt.
        /// </summary>
        internal static string PrecisionModeNoData {
            get {
                return ResourceManager.GetString("PrecisionModeNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die High reliability ähnelt.
        /// </summary>
        internal static string PrecisionModePerfect {
            get {
                return ResourceManager.GetString("PrecisionModePerfect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Compled ähnelt.
        /// </summary>
        internal static string StatusCompled {
            get {
                return ResourceManager.GetString("StatusCompled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Creation ähnelt.
        /// </summary>
        internal static string StatusCreation {
            get {
                return ResourceManager.GetString("StatusCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Drying ähnelt.
        /// </summary>
        internal static string StatusDrying {
            get {
                return ResourceManager.GetString("StatusDrying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die In Progress ähnelt.
        /// </summary>
        internal static string StatusInProgress {
            get {
                return ResourceManager.GetString("StatusInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pending ähnelt.
        /// </summary>
        internal static string StatusPending {
            get {
                return ResourceManager.GetString("StatusPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Prepare ähnelt.
        /// </summary>
        internal static string StatusPrepare {
            get {
                return ResourceManager.GetString("StatusPrepare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fetching Jobs ähnelt.
        /// </summary>
        internal static string TaskFetchJobs {
            get {
                return ResourceManager.GetString("TaskFetchJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Amount was not set. ähnelt.
        /// </summary>
        internal static string TimeCalcAmountNull {
            get {
                return ResourceManager.GetString("TimeCalcAmountNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Amount must be greater than 1. ähnelt.
        /// </summary>
        internal static string TimeCalcAmountToLow {
            get {
                return ResourceManager.GetString("TimeCalcAmountToLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Format maximum 52 x 100. ähnelt.
        /// </summary>
        internal static string TimeCalcFormatToLarge {
            get {
                return ResourceManager.GetString("TimeCalcFormatToLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Format at least A4. ähnelt.
        /// </summary>
        internal static string TimeCalcFormatToSmall {
            get {
                return ResourceManager.GetString("TimeCalcFormatToSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Passes was not set. ähnelt.
        /// </summary>
        internal static string TimeCalcIterationNull {
            get {
                return ResourceManager.GetString("TimeCalcIterationNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pass must have at least 1. ähnelt.
        /// </summary>
        internal static string TimeCalcIterationToLow {
            get {
                return ResourceManager.GetString("TimeCalcIterationToLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Paper Format Specified Incorrect. ähnelt.
        /// </summary>
        internal static string TimeCalcPaperFormatWrong {
            get {
                return ResourceManager.GetString("TimeCalcPaperFormatWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Runtime Calculation ähnelt.
        /// </summary>
        internal static string TimeCalcRuntimeCalculation {
            get {
                return ResourceManager.GetString("TimeCalcRuntimeCalculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Speed ​​must be at least 0.06. ähnelt.
        /// </summary>
        internal static string TimeCalcSpeedLow {
            get {
                return ResourceManager.GetString("TimeCalcSpeedLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Speed ​​was not set. ähnelt.
        /// </summary>
        internal static string TimeCalcSpeedNull {
            get {
                return ResourceManager.GetString("TimeCalcSpeedNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Speed ​​may not exceed 0.7. ähnelt.
        /// </summary>
        internal static string TimeCalcSpeeHight {
            get {
                return ResourceManager.GetString("TimeCalcSpeeHight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The running time must be over 1 second. ähnelt.
        /// </summary>
        internal static string TimeCalcTimeLow {
            get {
                return ResourceManager.GetString("TimeCalcTimeLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No data available. ähnelt.
        /// </summary>
        internal static string TimeCalculationNoDataLabel {
            get {
                return ResourceManager.GetString("TimeCalculationNoDataLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The last Values only in 5 cm steps ähnelt.
        /// </summary>
        internal static string TimeFormatToolTip {
            get {
                return ResourceManager.GetString("TimeFormatToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Time is calculating ähnelt.
        /// </summary>
        internal static string TitleTimeCalcCalculation {
            get {
                return ResourceManager.GetString("TitleTimeCalcCalculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Paper Format ähnelt.
        /// </summary>
        internal static string WaterLabelPaperFormat {
            get {
                return ResourceManager.GetString("WaterLabelPaperFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Runs ähnelt.
        /// </summary>
        internal static string WaterLabelRuns {
            get {
                return ResourceManager.GetString("WaterLabelRuns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mikron ähnelt.
        /// </summary>
        internal static string WaterLabelTimeMikron {
            get {
                return ResourceManager.GetString("WaterLabelTimeMikron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Amount ähnelt.
        /// </summary>
        internal static string WaterLabelTimeNumber {
            get {
                return ResourceManager.GetString("WaterLabelTimeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Speed ähnelt.
        /// </summary>
        internal static string WaterLabelTimeSpeed {
            get {
                return ResourceManager.GetString("WaterLabelTimeSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create Job ähnelt.
        /// </summary>
        internal static string WindowTitelCreateJob {
            get {
                return ResourceManager.GetString("WindowTitelCreateJob", resourceCulture);
            }
        }
    }
}
