// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Tauron.Application.ProjectManager.ApplicationServer.Data;

namespace Tauron.Application.ProjectManager.ApplicationServer.Migrations
{
    [DbContext(typeof(DatabaseImpl))]
    internal class DatabaseImplModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
            #pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ChangeDetector.SkipDetectChanges", "true")
                .HasAnnotation("ProductVersion", "2.1.0-preview2-30571");

            modelBuilder.Entity("Tauron.Application.ProjectManager.ApplicationServer.Data.PrivateEntitys.UserEntity", b =>
                                                                                                                      {
                                                                                                                          b.Property<string>("Id")
                                                                                                                           .ValueGeneratedOnAdd();

                                                                                                                          b.Property<string>("Password");

                                                                                                                          b.Property<string>("Salt");

                                                                                                                          b.HasKey("Id");

                                                                                                                          b.ToTable("Users");
                                                                                                                      });

            modelBuilder.Entity("Tauron.Application.ProjectManager.Data.Entitys.JobEntity", b =>
                                                                                            {
                                                                                                b.Property<string>("Id")
                                                                                                 .ValueGeneratedOnAdd();

                                                                                                b.Property<bool>("Importent");

                                                                                                b.Property<bool>("IsActive");

                                                                                                b.Property<string>("LongName");

                                                                                                b.Property<int>("Status");

                                                                                                b.Property<DateTime>("TargetDate");

                                                                                                b.HasKey("Id");

                                                                                                b.ToTable("Jobs");
                                                                                            });

            modelBuilder.Entity("Tauron.Application.ProjectManager.Data.Entitys.JobRunEntity", b =>
                                                                                               {
                                                                                                   b.Property<int>("Id")
                                                                                                    .ValueGeneratedOnAdd();

                                                                                                   b.Property<long>("Amount");

                                                                                                   b.Property<bool>("BigProblem");

                                                                                                   b.Property<TimeSpan>("EffectiveTime");

                                                                                                   b.Property<bool>("IsCompleted");

                                                                                                   b.Property<bool>("IsSaved");

                                                                                                   b.Property<int?>("IterationTime");

                                                                                                   b.Property<long>("Iterations");

                                                                                                   b.Property<string>("JobId");

                                                                                                   b.Property<int>("Length");

                                                                                                   b.Property<TimeSpan>("NormaizedTime");

                                                                                                   b.Property<bool>("Problem");

                                                                                                   b.Property<int?>("SetupTime");

                                                                                                   b.Property<double>("Speed");

                                                                                                   b.Property<DateTime>("StartTime");

                                                                                                   b.Property<int>("Width");

                                                                                                   b.HasKey("Id");

                                                                                                   b.HasIndex("JobId")
                                                                                                    .IsUnique();

                                                                                                   b.ToTable("Runs");
                                                                                               });

            modelBuilder.Entity("Tauron.Application.ProjectManager.Data.Entitys.SetupEntity", b =>
                                                                                              {
                                                                                                  b.Property<int>("Id")
                                                                                                   .ValueGeneratedOnAdd();

                                                                                                  b.Property<int>("SetupType");

                                                                                                  b.Property<DateTime>("StartTime");

                                                                                                  b.Property<int>("Value");

                                                                                                  b.HasKey("Id");

                                                                                                  b.ToTable("Setups");
                                                                                              });

            modelBuilder.Entity("Tauron.Application.ProjectManager.Data.Entitys.JobRunEntity", b =>
                                                                                               {
                                                                                                   b.HasOne("Tauron.Application.ProjectManager.Data.Entitys.JobEntity", "Job")
                                                                                                    .WithOne("JobRun")
                                                                                                    .HasForeignKey("Tauron.Application.ProjectManager.Data.Entitys.JobRunEntity", "JobId");
                                                                                               });
            #pragma warning restore 612, 618
        }
    }
}