//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tauron.MgiProjectManager.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppRes() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tauron.MgiProjectManager.Resources.AppRes", typeof(AppRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The following errors occurred whilst deleting role:  ähnelt.
        /// </summary>
        public static string AccountController_DeleteRole_Error {
            get {
                return ResourceManager.GetString("AccountController_DeleteRole_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Role cannot be deleted. Remove all users from this role and try again ähnelt.
        /// </summary>
        public static string AccountController_DeleteRole_Test {
            get {
                return ResourceManager.GetString("AccountController_DeleteRole_Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The following errors occurred whilst deleting user:  ähnelt.
        /// </summary>
        public static string AccountController_DeleteUser_Error {
            get {
                return ResourceManager.GetString("AccountController_DeleteUser_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die User cannot be deleted. Delete all associated Data from this user and try again ähnelt.
        /// </summary>
        public static string AccountController_DeleteUser_TestFailed {
            get {
                return ResourceManager.GetString("AccountController_DeleteUser_TestFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The following errors occurred whilst unblocking user:  ähnelt.
        /// </summary>
        public static string AccountController_UnblockUser_Error {
            get {
                return ResourceManager.GetString("AccountController_UnblockUser_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Conflicting role id in parameter and model data ähnelt.
        /// </summary>
        public static string AccountController_UpdateRole_ConflictigId {
            get {
                return ResourceManager.GetString("AccountController_UpdateRole_ConflictigId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Conflicting user ID in parameter and model data ähnelt.
        /// </summary>
        public static string AccountController_UpdateUser_IdMismatch {
            get {
                return ResourceManager.GetString("AccountController_UpdateUser_IdMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Current password is required when changing your own password ähnelt.
        /// </summary>
        public static string AccountController_UpdateUser_PasswordChanged {
            get {
                return ResourceManager.GetString("AccountController_UpdateUser_PasswordChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The username/password couple is invalid. ähnelt.
        /// </summary>
        public static string AccountController_UpdateUser_PasswordCheck {
            get {
                return ResourceManager.GetString("AccountController_UpdateUser_PasswordCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Current password is required when changing your own username ähnelt.
        /// </summary>
        public static string AccountController_UpdateUser_UserChanged {
            get {
                return ResourceManager.GetString("AccountController_UpdateUser_UserChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The following errors occurred whilst updating User Configurations:  ähnelt.
        /// </summary>
        public static string AccountController_UserPreferences_Error {
            get {
                return ResourceManager.GetString("AccountController_UserPreferences_Error", resourceCulture);
            }
        }
    }
}
