//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IISServiceManager.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IISServiceManager.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clsoe ähnelt.
        /// </summary>
        internal static string MainWindow_CloseContext {
            get {
                return ResourceManager.GetString("MainWindow_CloseContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Service Group ähnelt.
        /// </summary>
        internal static string MainWindow_ClusterSelector {
            get {
                return ResourceManager.GetString("MainWindow_ClusterSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Essential Services ähnelt.
        /// </summary>
        internal static string MainWindow_EssentialServices {
            get {
                return ResourceManager.GetString("MainWindow_EssentialServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Install ähnelt.
        /// </summary>
        internal static string MainWindow_InstallService {
            get {
                return ResourceManager.GetString("MainWindow_InstallService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Root path to install the web pages is required. ähnelt.
        /// </summary>
        internal static string MainWindow_Load_SelectPathError {
            get {
                return ResourceManager.GetString("MainWindow_Load_SelectPathError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Services ähnelt.
        /// </summary>
        internal static string MainWindow_NormalServices {
            get {
                return ResourceManager.GetString("MainWindow_NormalServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Installing... ähnelt.
        /// </summary>
        internal static string MainWindow_Progress_Installing {
            get {
                return ResourceManager.GetString("MainWindow_Progress_Installing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Uninstalling... ähnelt.
        /// </summary>
        internal static string MainWindow_Progress_UnInstalling {
            get {
                return ResourceManager.GetString("MainWindow_Progress_UnInstalling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Updating... ähnelt.
        /// </summary>
        internal static string MainWindow_Progress_Updating {
            get {
                return ResourceManager.GetString("MainWindow_Progress_Updating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die UnInstall ähnelt.
        /// </summary>
        internal static string MainWindow_UninstallService {
            get {
                return ResourceManager.GetString("MainWindow_UninstallService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update All ähnelt.
        /// </summary>
        internal static string MainWindow_UpdateAll {
            get {
                return ResourceManager.GetString("MainWindow_UpdateAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update ähnelt.
        /// </summary>
        internal static string MainWindow_UpdateService {
            get {
                return ResourceManager.GetString("MainWindow_UpdateService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Check Prerequisites ähnelt.
        /// </summary>
        internal static string MainWindow_Warning_CheckPrerequisites {
            get {
                return ResourceManager.GetString("MainWindow_Warning_CheckPrerequisites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Loading... ähnelt.
        /// </summary>
        internal static string Progress_Common_Loading {
            get {
                return ResourceManager.GetString("Progress_Common_Loading", resourceCulture);
            }
        }
    }
}
